### ISSUE TITLE
Unable to discover IPsec cipSecTunnelTable on a Cisco router

### ISSUE THREAD

**Issue by borisstoqnov** [iTransformers/netTransformer#19]
It seems that even though the router is discovered and the raw-data populated the IPsec information is missing.

There are no errors while discover-now runs and the device is properly discovered as Cisco:
match Resource=cisco, device params: {deviceType=cisco, ipAddress=192.168.3.2, deviceName=R1}

The parameter exists in the configuration editor.
        <discovery-method name="IPSEC">
            cipSecTunnelTable,cikeTunnelTable

However the cipSecTunnelTable and cikeTunnelTable are not populated in the raw-data.xml

**Comment by niau** [comment]
@borisstoqnov  you should be good now. Please try again!

**Comment by niau** [comment]
@borisstoqnov  please verify and if ok close the issue. Would be useful if you paste here the pieces of the corresponding raw-data and device-data  xml  related to the generated IPSEC neighbor.

**Comment by niau** [comment]
Have not heard anything else thus assuming that works. So closing it now !

**Comment by borisstoqnov** [comment]
Issue is fixed, thanks!
