### ISSUE TITLE
mvn package command not working

### ISSUE THREAD

**Issue by sudharanis287** [iTransformers/netTransformer#21]
hi ,
After downloading the netTransformer  mvn package is not working.

Errror building the POM file I am getting.Please help in resolve this issue

Thanks

**Comment by niau** [comment]
Please provide us with more details about your environment and the output
of the package step.
Thanks

**Comment by sudharanis287** [comment]
Hi 

I am using JDK 1.7 ,maven 2.2.1 ,I downloaded the netTranformers zip and followed below steps
cd netTransformer-master/netTransformer-master
mvn package
But mvn package output was 

[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: org.apache.maven.plugins:maven-site-plugin

Reason: POM 'org.apache.maven.plugins:maven-site-plugin' not found in repository
: Unable to download the artifact from any repository

  org.apache.maven.plugins:maven-site-plugin:pom:3.1

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  iTransformers Repo (http://repo.itransformers.net/repos)

 for project org.apache.maven.plugins:maven-site-plugin


[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Thu Apr 21 15:29:00 IST 2016
[INFO] Final Memory: 2M/15M
[INFO] ------------------------------------------------------------------------



Can you please tell me where I am going wrong ,should I need to add anything
and I have a .m2/repository folder as well with org/apache/plugins/maven-site-plugins.

Thanks,
Sudha

**Comment by niau** [comment]
Hi Sudha, 
 I believe we have switched to java 8 and also is preferable to use maven 3+

Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T22:10:27+02:00)
Maven home: /usr/share/apache-maven-3.3.1
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"

**Comment by sudharanis287** [comment]
Hi Niau,
Yes I tried to change JDK 1.8 and maven 3.3.9 then it followed with below error.
INFO] netTransformer ..................................... SUCCESS [  0.008 s]
[INFO] utils .............................................. FAILURE [  1.832 s]
[INFO] resourceManager .................................... SKIPPED
[INFO] bgpPeeringMap ...................................... SKIPPED
[INFO] postDiscoverer ..................................... SKIPPED
[INFO] iDiscover .......................................... SKIPPED
[INFO] iTopologyManager ................................... SKIPPED
[INFO] topologyManagerConfig .............................. SKIPPED
[INFO] rightClickAPI ...................................... SKIPPED
[INFO] parameterFactory ................................... SKIPPED
[INFO] fulfilmentFactory .................................. SKIPPED
[INFO] topologyViewer ..................................... SKIPPED
[INFO] rightClick ......................................... SKIPPED
[INFO] launcher ........................................... SKIPPED
[INFO] distribution ....................................... SKIPPED
[INFO] iAssertions ........................................ SKIPPED
[INFO] wsitransformer ..................................... SKIPPED
[INFO] ideas .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.183 s
[INFO] Finished at: 2016-04-21T08:57:25+05:30
[INFO] Final Memory: 6M/17M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its
 dependencies could not be resolved: Failed to read artifact descriptor for org.
apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact
 org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https:
//repo.maven.apache.org/maven2): this is usually a temporary error during hostname resolution and means local server .


Please help in resolving this.
And I have some requirement can you please help me in coding that I am very new to networking java.

I need some help to go forward.
Will be waiting for your reply.

Thanks,
Sudha

**Comment by niau** [comment]
It seems that you maven is unable to connect to the central maven
repository http://repo.maven.org/maven2 <http://repo1.maven.org/maven2>.

May you try to delete everyting in folder ~/.m2/repository/

And then try again.

On Fri, Apr 22, 2016 at 6:19 AM, sudharanis287 <notifications@github.com>
wrote:

> Hi Niau,
> Yes I tried to change JDK 1.8 and maven 3.3.9 then it followed with below
> error.
> INFO] netTransformer ..................................... SUCCESS [ 0.008
> s]
> [INFO] utils .............................................. FAILURE [
> 1.832 s]
> [INFO] resourceManager .................................... SKIPPED
> [INFO] bgpPeeringMap ...................................... SKIPPED
> [INFO] postDiscoverer ..................................... SKIPPED
> [INFO] iDiscover .......................................... SKIPPED
> [INFO] iTopologyManager ................................... SKIPPED
> [INFO] topologyManagerConfig .............................. SKIPPED
> [INFO] rightClickAPI ...................................... SKIPPED
> [INFO] parameterFactory ................................... SKIPPED
> [INFO] fulfilmentFactory .................................. SKIPPED
> [INFO] topologyViewer ..................................... SKIPPED
> [INFO] rightClick ......................................... SKIPPED
> [INFO] launcher ........................................... SKIPPED
> [INFO] distribution ....................................... SKIPPED
> [INFO] iAssertions ........................................ SKIPPED
> [INFO] wsitransformer ..................................... SKIPPED
> [INFO] ideas .............................................. SKIPPED
> [INFO]
> ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO]
> ------------------------------------------------------------------------
> [INFO] Total time: 2.183 s
> [INFO] Finished at: 2016-04-21T08:57:25+05:30
> [INFO] Final Memory: 6M/17M
> [INFO]
> ------------------------------------------------------------------------
> [ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one
> of its
> dependencies could not be resolved: Failed to read artifact descriptor for
> org.
> apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer
> artifact
> org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central
> (https:
> //repo.maven.apache.org/maven2): this is usually a temporary error during
> hostname resolution and means local server .
>
> Please help in resolving this.
> And I have some requirement can you please help me in coding that I am
> very new to networking java.
>
> I need some help to go forward.
> Will be waiting for your reply.
>
> Thanks,
> Sudha
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/iTransformers/netTransformer/issues/21#issuecomment-213226964>
>



-- 
BR,

Nikolay Milovanov
Email: n.milovanov@gmail.com

**Comment by sudharanis287** [comment]
Hi Niau,

As per your suggestion I deleted all the files in ~/.m2/repository,but still facing the mvn package issue.

Anything I am missing?

Thanks,
Sudha

**Comment by sudharanis287** [comment]
Hi Niau,

As per your suggestion I tried to delete everything under folder ~/.m2/repository/ .But still facing the same issue.
From IE also I am unable to access the central maven repository  http://repo.maven.org/maven2 <http://repo1.maven.org/maven2>.

Anything I am missing please suggest.

Thanks,
Sudha

**Comment by sudharanis287** [comment]
Hi Niau,

I need some help in writing the network java application Can I share my requirement?

Please guide me what need to be done so I will go forward .

Thanks,
Sudha

**Comment by niau** [comment]
Hi Sudha,

Sure you can share your requirement but please use the forum
<http://forum.itransformers.net/fluxbb/> instead of a github issues.

Regarding your real issue. Maven is using java settings to access the
internet.

You issue might be due to a proxy or firewall configured on your host but
not on the java.

With essence you should configure in your maven settings the same kind of
proxy that you might have in your browser.

Otherwise maven central is the most central maven repository in the world.

You can try to list for example the plugins there by going to the following
link

http://repo1.maven.org/maven2/org/apache/maven/plugins/







On Fri, Apr 22, 2016 at 7:13 AM, sudharanis287 <notifications@github.com>
wrote:

> Hi Niau,
>
> I need some help in writing the network java application Can I share my
> requirement?
>
> Please guide me what need to be done so I will go forward .
>
> Thanks,
> Sudha
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/iTransformers/netTransformer/issues/21#issuecomment-213243284>
>



-- 
BR,

Nikolay Milovanov
Email: n.milovanov@gmail.com

**Comment by sudharanis287** [comment]
Hi Niau,

As you told Maven is using java settings to access the internet,In my system proxy setting is not enabled I checked in IE->Internet options->Connections-Proxy Its not checked


And Can you please help in configuring the maven settings.
Thanks,
Sudha

**Comment by sudharanis287** [comment]
Hi Niau,

I shared my requirement in forum under Developlmen.Can you please help I am very new to network java.Tell me the step by step process to start with and which all the jar files need to be there.

Will be waiting for your reply.Thanks a lot in advance.
Thanks,
Sudha

**Comment by niau** [comment]
Sorry Sudha,

For me it is building and also for our CI server it is bulding thus the
current codeship build status is green.

 I have not clue what might be wrong from your side. Whatever it is it
relates to your environment.

Nikolay

On Fri, Apr 22, 2016 at 10:12 AM, sudharanis287 <notifications@github.com>
wrote:

> Hi Niau,
>
> As you told Maven is using java settings to access the internet,In my
> system proxy setting is not enabled I checked in IE->Internet
> options->Connections-Proxy Its not checked
>
> And Can you please help in configuring the maven settings.
> Thanks,
> Sudha
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/iTransformers/netTransformer/issues/21#issuecomment-213295935>
>



-- 
BR,

Nikolay Milovanov
Email: n.milovanov@gmail.com

**Comment by sudharanis287** [comment]
Hi Niau,

Thanks a lot for your response.I need a lot of favour from your side .

I need your help in my requirement coding please check the forum under Development Discussion and reply if its possible .I will be waiting for your response.

Thanks ,
Sudha

**Comment by sudharanis287** [comment]
Hi Niau,

And relating mvn package error.I don't have seetings.xml under ~/.m2/
Is this a problem?

If so please share the settings.xml .

Thanks,
Sudha

**Comment by niau** [comment]
I can't share my file since there are a lot of details there.

However your maven install should produce the settings.xml for you. Just
find the file and copy it to .m2 folder.
https://maven.apache.org/settings.html

Personally I doubt that this is your issue but you may try. Have you passed
through maven in 5 mins guide?

Nikolay



On Fri, Apr 22, 2016 at 10:27 AM, sudharanis287 <notifications@github.com>
wrote:

> Hi Niau,
>
> And relating mvn package error.I don't have seetings.xml under ~/.m2/
> Is this a problem?
>
> If so please share the settings.xml .
>
> Thanks,
> Sudha
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/iTransformers/netTransformer/issues/21#issuecomment-213301328>
>



-- 
BR,

Nikolay Milovanov
Email: n.milovanov@gmail.com

**Comment by sudharanis287** [comment]
Hi Niau,

Yes I have done with the maven in 5 min .

Thanks,
Sudha

**Comment by sudharanis287** [comment]
Yes there is settings.xml file under maven 3.3.9/conf path
I copied the settings.xml file in ~/.m2/ folder but no use.

**Comment by niau** [comment]
Sudha here is not the place to learn how to configure and use maven. I can ensure you that in our setup there is nothing special. Please post your issues on http://www.java-forums.org/apache-maven/ or http://stackoverflow.com/. 

I am closing that one now.
