### ISSUE TITLE
DiscoveryWizard first connection parameter blank

### ISSUE THREAD

**Issue by borisstoqnov** [iTransformers/netTransformer#27]
When you choose a resource the first Connection Parameter is always blank.

As a workaround I added a random resource like <connection-params connection-type="TEST"> which allows me to use the rest.

![discovernowparameter](https://cloud.githubusercontent.com/assets/13061359/15207538/8d10c11c-182f-11e6-97c2-0247a6cf36a8.png)

**Comment by niau** [comment]
@vasil-yordanov  may you have a look on that one. I tried to figure out why is it so but no luck...
