### ISSUE TITLE
ResourceResolver hardcoded to get first element

### ISSUE THREAD

**Issue by borisstoqnov** [iTransformers/netTransformer#28]
iTopologyManager -> rightClick -> Resource Resolver

ConnectionParamsType connParamsType = resource.getConnectionParams().get(0);

This leads to incorrect parameters being passed when trying to configure hostname through telnet as it always uses the first connection parameter in the xml.

As a workaround given that these changes are implemented using telnet added the following:
            List<ConnectionParamsType> connParamsTypes = resource.getConnectionParams();

            for (ConnectionParamsType connParamsType : connParamsTypes) {

                if (connParamsType.getConnectionType().equals("telnet")){

                    Map<String, String> connParams = new HashMap<String, String>();
                    for (ParamType param : connParamsType.getParam()) {
                        connParams.put(param.getName(), param.getValue());
                    }

                    connParams.put("discoveredIPv4Address", graphMLParams.get("discoveredIPv4Address"));
                    connParams.put("protocol", connParamsType.getConnectionType());
                    return connParams;
                }
            }

**Comment by niau** [comment]
Please @borisstoqnov  please verify and try again.

**Comment by borisstoqnov** [comment]
This is resolved.
