### ISSUE TITLE
viewer-config handlerclass does not accept class names starting with capital letters

### ISSUE THREAD

**Issue by borisstoqnov** [iTransformers/netTransformer#50]
viewer-config:

doesn't work:
<rightClickItem name="Neighbor Finder" handlerClass="NeighbourFinderByMethod">
Give an error that no bean with that name is found.

works:
rightClickItem name="Neighbor Finder" handlerClass="neighbourFinderByMethod">

**Comment by niau** [comment]
@borisstoqnov the handlerClass should be equal to the bean name and not to the class name. 
For example: 

In rightClick/rightClick.xml you got:
```
    <bean id="neighbourFinderByMethod" class="net.itransformers.topologyviewer.rightclick.impl.ipsec.NeighbourFinderByMethod">
    </bean>
```
So in toplogyViewer should be:

           ```
 <rightClickItem name="Neighbor Finder" handlerClass="neighbourFinderByMethod">
                <param name="Discovery Method">IPSEC</param>

            </rightClickItem>
```

If there is a bug it would be in the naming convening in topologyViewer.xml. Should be written not handlerClass but either handlerObject or handlerBean. 
What do you think @vasil-yordanov?
