### ISSUE TITLE
User Guide and cloned repo do not match

### ISSUE THREAD

**Issue by compata** [iTransformers/netTransformer#82]
User Guide, "Step 1 ... you will see the following folder structure." Not close to what I see in the repo.

On Unix, run bin/netTransformer.sh. I find that in netTransformer/iTopologyManager/topologyViewer/conf/bat. when I run it (./netTransformer.sh), I see,
```
Echo
Error: Could not find or load main class net.itransformers.topologyvierwer.gui.launcher.TopologyViewerLauncher
```
I'm not incapable of adapting but this seems to require more effort than expected.

**Comment by compata** [comment]
Nevermind. Somehow I was misled that cloning the repo was equivalent to downloading the package.

**Comment by niau** [comment]
Hi compata, 

It is not. You can start a discovery process from command line by https://github.com/iTransformers/netTransformer/blob/master/iDiscover/cliDiscoveryLauncher/src/main/java/net/itransformer/cli_discovery_launcher/CliDiscoveryLauncher.java

If you want to run the GUI the correct class is:
https://github.com/iTransformers/netTransformer/blob/master/iTopologyManager/launcher/src/main/java/net.itransformers.topologyvierwer.gui.launcher/TopologyViewerLauncher.java

Let me know if you have more questions. 
The user guide is a bit old I admit ;)
Now the efforts were to make it working in a browser. For example you may try the docker build.
https://github.com/iTransformers/netTransformer/wiki/netTransformer-on-Docker
